# Generated by Django 2.2.7 on 2019-11-20 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gfarm.validators
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('rg', models.CharField(max_length=14, verbose_name='RG')),
                ('cpf', models.CharField(max_length=14, validators=[gfarm.validators.validate_CPF], verbose_name='CPF')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Feminino')], max_length=10)),
                ('funcao', models.CharField(choices=[('Proprietário', 'Proprietário'), ('Funcionário', 'Funcionário')], max_length=15, verbose_name='Função')),
                ('telefone', models.CharField(help_text='(xx)xxxx-xxxx', max_length=20, verbose_name='Telefone')),
                ('image', models.ImageField(default='default.jpg', upload_to=users.models.user_directory_path, verbose_name='Imagem')),
                ('user', models.OneToOneField(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
