# Generated by Django 2.1.7 on 2019-11-20 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gfarm', '0003_auto_20191120_1702'),
        ('movimentacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada_Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_entrada', models.FloatField()),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gfarm.Medicamento')),
                ('quantidade_estoque_atual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estoque_atual', to='gfarm.Medicamento')),
            ],
        ),
    ]
