# Generated by Django 2.1.7 on 2019-11-20 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gfarm', '0002_remove_medicamento_novacompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='medicamento',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='alimento',
            name='principioAtivo',
            field=models.TextField(max_length=1000, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='categoriamedicamento',
            name='tipomedicamento',
            field=models.CharField(max_length=100, verbose_name='Tipo Medicamento'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='principio_ativo',
            field=models.TextField(max_length=1000, verbose_name=' Principio Ativo'),
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
    ]
