# Generated by Django 2.1.7 on 2019-11-26 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gfarm', '0004_auto_20191120_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gfarm.Local', verbose_name='Barracão'),
        ),
    ]
