# Generated by Django 2.1.7 on 2019-11-26 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gfarm', '0005_auto_20191126_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gfarm.Local', verbose_name='Barracão'),
        ),
    ]
